before_script:
  - touch .env
  - echo 'ANALYTICS_ID=foobar' >> .env
  - echo 'ANALYTICS_SECRET=barfoo' >> .env
services:
  - mongodb
rvm:
  - '1.9.3'
  - '2.0.0'
script: bundle exec rspec spec -f documentation
